--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: asks; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE asks (
    id integer NOT NULL,
    question text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.asks OWNER TO postgres;

--
-- Name: asks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE asks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.asks_id_seq OWNER TO postgres;

--
-- Name: asks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE asks_id_seq OWNED BY asks.id;


--
-- Name: hexes; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE hexes (
    hex_id integer NOT NULL,
    name text NOT NULL,
    meaning text NOT NULL,
    keywords text NOT NULL,
    symbol text NOT NULL,
    top text NOT NULL,
    bottom text NOT NULL
);


ALTER TABLE public.hexes OWNER TO postgres;

--
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE questions (
    id integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    ask text
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.questions_id_seq OWNER TO postgres;

--
-- Name: questions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE questions_id_seq OWNED BY questions.id;


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE schema_migrations (
    version character varying(255) NOT NULL
);


ALTER TABLE public.schema_migrations OWNER TO postgres;

--
-- Name: id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY asks ALTER COLUMN id SET DEFAULT nextval('asks_id_seq'::regclass);


--
-- Name: id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY questions ALTER COLUMN id SET DEFAULT nextval('questions_id_seq'::regclass);


--
-- Data for Name: asks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY asks (id, question, created_at, updated_at) FROM stdin;
1	Test First one.	2014-06-11 08:44:52.649172	2014-06-11 08:44:52.649172
2	a;dfkj	2014-06-11 17:38:20.261998	2014-06-11 17:38:20.261998
\.


--
-- Name: asks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('asks_id_seq', 2, true);


--
-- Data for Name: hexes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY hexes (hex_id, name, meaning, keywords, symbol, top, bottom) FROM stdin;
1	Ch'ien  The Creative	The first hexagram is made up of six unbroken lines. These unbroken lines stand for the primal power, which is light-giving, active, strong, and of the spirit. The hexagram is consistently strong in character, and since it is without weakness, its essence is power or energy. Its image is heaven. Its energy is represented as unrestricted by any fixed conditions in space and is therefore conceived of as motion. Time is regarded as the basis of this motion. Thus the hexagram includes also the power of time and the power of persisting in time, that is, duration. The power represented by the hexagram is to be interpreted in a dual sense in terms of its action on the universe and of its action on the world of men. In relation to the universe, the hexagram expresses the strong, creative action of the Deity. In relation to the human world, it denotes the creative action of the holy man or sage, of the ruler or leader of men, who through his power awakens and develops their higher nature.	The Creative works sublime success, Furthering through perseverance.	The movement of heaven is full of power. Thus the superior man makes himself strong and untiring.	Above Ch'ien the Creative, Heaven	Below Ch'ien the Creative, Heaven
2	K'un  The Receptive	This hexagram is made up of broken lines only. The broken lines represents the dark, yielding, receptive primal power of yin. The attribute of the hexagram is devotion; its image is the earth. It is the perfect complement of The Creative the complement, not the opposite, for the Receptive does not combat the Creative but completes it . It represents nature in contrast to spirit, earth in contrast to heaven, space as against time, the female-maternal as against the male-paternal. However, as applied to human affairs, the principle of this complementary relationship is found not only in the relation between man and woman, but also in that between prince and minister and between father and son. Indeed, even in the individual this duality appears in the coexistence of the spiritual world and the world of the senses. But strictly speaking there is no real dualism here, because there is a clearly defined hierarchic relationship between the two principles. In itself of course the Receptive is just as important as the Creative, but the attribute of devotion defines the place occupied by this primal power in relation to the Creative. For the Receptive must be activated and led by the Creative; then it is productive of good. Only when it abandons this position and tries to stand as an equal side by side with the Creative, does it become evil. The result then is opposition to and struggle against the Creative, which is productive of evil to both.	The Receptive brings about sublime success, Furthering through the perseverance of a mare. If the superior man undertakes something and tries to lead, He goes astray; But if he follows, he finds guidance. It is favorable to find friends in the west and south, To forego friends in the east and north. Quiet perseverance brings good fortune.	The earth's condition is receptive devotion. Thus the superior man who has breadth of character Carries the outer world.	Above K'un the Receptive, Earth	Below K'un the Receptive, Earth
3	Chun  Difficulty at the Beginning	The name of the hexagram, Chun, really connotes a blade of grass pushing against an obstacle as it sprouts out of the earth--hence the meaning, difficulty at the beginning. The hexagram indicates the way in which heaven and earth bring forth individual beings. It is their first meeting, which is beset with difficulties. The lower trigram Chen is the Arousing; its motion is upward and its image is thunder. The upper trigram K'an stands for the Abysmal, the dangerous. Its motion is downward and its image is rain. The situation points to teeming, chaotic profusion; thunder and rain fill the air. But the chaos clears up. While the Abysmal sinks, the upward movement eventually passes beyond the danger. A thunderstorm brings release from tension, and all things breathe freely again.	Difficulty at the Beginning works supreme success, Furthering through perseverance. Nothing should be undertaken. It furthers one to appoint helpers.	Clouds and thunder: The image of Difficulty at the Beginning. Thus the superior man Brings order out of confusion.	Above K'an the abysmal, Water	Below Chen the Arousing, Thunder
4	Meng  Youthful Folly	In this hexagram we are reminded of youth and folly in two different ways. The image of the upper trigram, Ken, is the mountain, that of the lower, K'an, is water; the spring rising at the foot of the mountain is the image of inexperienced youth. Keeping still is the attribute of the upper trigram; that of the lower is the abyss, danger. Stopping in perplexity on the brink of a dangerous abyss is a symbol of the folly of youth. However, the two trigrams also show the way of overcoming the follies of youth. Water is something that of necessity flows on. When the spring gushes forth, it does not know at first where it will go. But its steady flow fills up the deep place blocking its progress, and success is attained.	Youthful Folly has success. It is not I who seek the young fool; The young fool seeks me. At the first oracle I inform him. If he asks two or three times, it is importunity. If he importunes, I give him no information. Perseverance furthers.	A spring wells up at the foot of the mountain: The image of Youth. Thus the superior man fosters his character By thoroughness in all that he does.	Above Ken Keeping Still, Mountain	Below K'an the abysmal, Water
5	Hsu  Waiting (Nourishment)	All beings have need of nourishment from above. But the gift of food comes in its own time, and for this one must wait. This hexagram shows the clouds in the heavens, giving rain to refresh all that grows and to provide mankind with food and drink. The rain will come in its own time. We cannot make it come; we have to wait for it. The idea of waiting is further suggested by the attributes of the two trigrams--strength within, danger in from. Strength in the face of danger does not plunge ahead but bides its time, whereas weakness in the face of danger grows agitated and has not the patience to wait.	Waiting. If you are sincere, You have light and success. Perseverance brings good fortune. It furthers one to cross the great water.	Clouds rise up to heaven: The image of Waiting. Thus the superior man eats and drinks, Is joyous and of good cheer.	Above K'an the abysmal, Water	Below Ch'ien the Creative, Heaven
6	Sung  Conflict	The upper trigram, whose image is heaven, has an upward movement; the lower trigram, water, in accordance with its nature tends downward. Thus the two halves move away from each other, giving rise to the idea of conflict. The attribute of the Creative is strength, that of the Abysmal is danger, guile. Where cunning has force before it, there is conflict. A third indication of conflict, in terms of character, is presented by the combination of deep cunning within and fixed determination outwardly. A person of this character will certainly be quarrelsome.	Conflict. You are sincere And are being obstructed. A cautious halt halfway brings good fortune. Going through to the end brings misfortune. It furthers one to see the great man. It does not further one to cross the great water.	Heaven and water go their opposite ways: The image of Conflict. Thus in all his transactions the superior man Carefully considers the beginning.	Above Ch'ien the Creative, Heaven	Below K'an the abysmal, Water
38	K'uei  Opposition	This hexagram is composed of the trigram Li above, i.e., flame, which burns upward, and Tui below, i.e., the lake, which seeps downward. These two movements are indirect contrast. Furthermore, Li is the second daughter and Tui the youngest daughter, and although they live in the same house they belong to different men; hence their wills are not the same but are divergently directed.	Opposition. In small matters, good fortune.	Above, fire; below. The lake. The image of Opposition. Thus amid all fellowship the superior man retains his individuality.	Above Li the Clinging, Flame	Below Tui the Joyous, Lake
7	Shih  The Army	This hexagram is made up of the trigrams K'an, water, and K'un, earth, and thus it symbolizes the ground water stored up in the earth. In the same way military strength is stored up in the mass of the people--invisible in times of peace but always ready for use as a source of power. The attributes of the two trig rams are danger inside and obedience must prevail outside. Of the individual lines, the one that controls the hexagram is the strong nine in the second place, to which the other lines, all yielding, are subordinate. This line indicates a commander, because it stands in the middle of one of the two trigrams. But since it is in the lower rather than the upper trigram, it represents not the ruler but the efficient general, who maintains obedience in the army by his authority.	The Army. The army needs perseverance And a strong man. Good fortune without blame.	In the middle of the earth is water: The image of The Army. Thus the superior man increases his masses By generosity toward the people.	Above K'un the Receptive, Earth	Below K'an the abysmal, Water
8	Pi  Holding Together (union)	The waters on the surface of the earth flow together wherever they can, as for example in the ocean, where all the rivers come together. Symbolically this connotes holding together and the laws that regulate it. The same idea is suggested by the fact that all the lines of the hexagram except the fifth, the place of the ruler, are yielding. The yielding lines hold together because they are influenced by a man of strong will in the leading position, a man who is their center of union. Moreover, this strong and guiding personality in turn holds together with the others, finding in them the complement of his own nature.	Holding Togeather (Union) brings good fortune. Inquire of the oracle once again Whether you possess sublimity, constancy, and perseverance; Then there is no blame. Those who are uncertain gradually join. Whoever come too late Meets with misfortune.	On the earth is water: The image of Holding Togeather. Thus the kings of antiquity Bestowed the different states as fiefs And cultivated friendly relations With the feudal lords.	Above K'an the abysmal, Water	Below K'un the Receptive, Earth
9	Hsiao Chu  The Taming Power of the Small	This hexagram means the force of the small--the power of the shadowy--that restrains, tames, impedes. A weak line in the fourth place, that of the minister, holds the five strong lines in check. In the Image it is the wind blowing across the sky. The wind restrains the clouds, the rising breath of the Creative, and makes them grow dense, but as yet is not strong enough to turn them to rain. The hexagram presents a configuration of circumstances in which a strong element is temporarily held in leash by a weak element. It is only through gentleness that this can have a successful outcome.	The Taming Power of the Small has success, dense clouds, no rain from our western region.	The wind drives across heaven: The image of The Taming Power of the Small. Thus the superior man Refines the outward aspect of his nature.	Above Sun the Gentle, Wind	Below Ch'ien the Creative, Heaven
10	Lu  Treading (conduct)	The name of the hexagram means on the one hand the right way of conducting oneself. Heaven, the father, is above, and the lake, the youngest daughter, is below. This shows the difference between high and low, upon which composure correct social conduct, depends. On the other hand the word for the name of the hexagram, Treading, means literally treading upon something. The small and cheerful [Tui] treads upon the large and strong [Ch'ien]. The direction of movement of the two primary trigrams is upward. The fact that the strong treads on the weak is not mentioned in the Book of Changes, because it is taken for granted. For the weak to take a stand against the strong is not dangerous here, because it happened in good humor [Tui] and without presumption, so that the strong man is not irritated but takes it all in good part.	Treading. Treading upon the tail of the tiger. It does not bite the man. Success.	Heaven above, the lake below: The image of Treading. Thus the superior man discriminates between high and low and thereby fortifies the thinking of the people.	Above Ch'ien the Creative, Heaven	Below Tui the Joyous, Lake
11	T'ai  Peace	The Receptive, which moves downward, stands above; the Creative, which moves upward, is below. Hence their influences meet and are in harmony, so that all living things bloom and prosper. This hexagram belongs to the first month (February-March), at which time the forces of nature prepare the new spring.	Peace. The small departs, The great approaches. Good fortune. Success.	Heaven and earth unite: the image of Peace. Thus the ruler divides and completes the course of heaven and earth, and so aids the people.	Above K'un the Receptive, Earth	Below Ch'ien the Creative, Heaven
12	P'i  Standstill (Stagnation)	This hexagram is the opposite of the preceding one. Heaven is above, drawing farther and farther away, while the earth below sinks farther into the depths. The creative powers are not in relation. It is a time of standstill and decline. This hexagram is linked with the seventh month (August-September), when the year has passed its zenith and autumnal decay is setting in.	Standstill. Evil people do not further The perseverance of the superior man. The great departs; the small approaches.	Heaven and earth do not unite: The image of Standstill. Thus the superior man falls back upon his inner worth in order to escape the difficulties. He does not permit himself to be honored with revenue.	Above Ch'ien the Creative, Heaven	Below K'un the Receptive, Earth
13	T'ung Jen  Fellowship with Men	The image of the upper trigram Ch'ien is heaven, and that of the lower, Li, is flame. It is the nature of fire to flame up to the heaven. This gives the idea of fellowship. It is the second line that, by virtue of its central character, unites the five strong lines around it. This hexagram forms a complement to Shih, The Army (7). In the latter, danger is within and obedience without the character of a warlike army, which, in order to hold together, needs one strong man among the many who are weak. Here, clarity is within and strength without--the character of a peaceful union of men, which, in order to hold together, needs one yielding nature among many firm persons.	Fellowship with Men in the open. Success. It furthers one to cross the great water. The perseverance of the superior man furthers.	Heaven together with fire: The image of Fellowship with Men. Thus the superior man organizes the clans and makes distinctions between things.	Above Ch'ien the Creative, Heaven	Below Li the Clinging, Flame
14	Ta Yu  Possession in Great Measure	The fire in heaven above shines far, and all things stand out in the light and become manifest. The weak fifth line occupies the place of honor and all the strong lines are in accord with it. All things come to the man who is modest and kind in a high position.	Possession in Great Measure. Supreme success.	Fire in heaven above: the image of Possession in Great Measure. Thus the superior man curbs evil and furthers good, And thereby obeys the benevolent will of heaven.	Above Li the Clinging, Flame	Below Ch'ien the Creative, Heaven
15	Ch'ien  Modesty	This hexagram is made up of the trigrams Ken, Keeping Still, mountain, and K'un. The mountain is the youngest son of the Creative, the representative of heaven and earth. It dispenses the blessings of heaven, the clouds and rain that gather round its summit, and thereafter shines forth radiant with heavenly light. This shows what modesty is and how it functions in great and strong men. K'un, the earth, stands above. Lowliness is a quality of the earth: this is the very reason why it appears in this hexagram as exalted, by being placed above the mountain. This shows how modesty functions in lowly, simple people: they are lifted up by it.	Modesty creates success. The superior man carries things through.	Within the earth, a mountain: The image of Modesty. Thus the superior man reduces that which is too much, and augments that which is too little. He weighs things and makes them equal.	Above K'un the Receptive, Earth	Below Ken Keeping Still, Mountain
16	Yu  Enthusiasm	The strong line in the fourth place, that of the leading official, meets with response and obedience from all the other lines, which are all weak. The attribute of the upper trigram, Chen, is movement; the attributes of K'un, the lower, are obedience and devotion. This begins a movement that meets with devotion and therefore inspires enthusiasm, carrying all with it. Of great importance, furthermore, is the law of movement along the line of least resistance, which in this hexagram is enunciated as the law for natural events and for human life.	Enthusiasm. It furthers one to install helpers and to set armies marching.	Thunder comes resounding out of the earth: The image of Enthusiasm. Thus the ancient kings made music In order to honor merit, and offered it with splendor to the Supreme Deity, Inviting their ancestors to be present.	Above Chen the Arousing, Thunder	Below K'un the Receptive, Earth
17	Sui  Following	The trigram Tui, the Joyous, whose attribute is gladness, is above; Chen, the Arousing, which has the attribute of movement, is below. Joy in movement induces following. The Joyous is the youngest daughter, while the Arousing is the eldest son. An older man defers to a young girl and shows her consideration. By this he moves her to follow him.	Following has supreme success. Perseverance furthers. No blame.	Thunder in the middle of the lake: The image of Following. Thus the superior man at nightfall Goes indoors for rest and recuperation.	Above Tui the Joyous, Lake	Below Chen the Arousing, Thunder
18	Ku  Work on what has been spoiled (Decay)	The Chinese character ku represents a bowl in whose contents worms are breeding. This means decay. It is come about because the gentle indifference in the lower trigram has come together with the rigid inertia of the upper, and the result is stagnation. Since this implies guilt, the conditions embody a demand for removal of the cause. Hence the meaning of the hexagram is not simply 'what has been spoiled' but 'work on what has been spoiled'.	Work on what has been spoiled Has supreme success. It furthers one to cross the great water; Before the starting point, three days. After the starting point, three days.	The wind blows low on the mountain: The image of Decay. Thus the superior man stirs up the people and strengthens their spirit.	Above Ken Keeping Still, Mountain	Below Sun the Gentle, Wind
19	Lin  Approach	The Chinese word lin has a range of meanings that is not exhausted by any single word of another language. The ancient explanations in the Book of Changes give as its first meaning, 'becoming great.' What becomes great are the two strong lines growing into the hexagram from below; the light-giving power expands with them. The meaning is then further extended to include the concept of approach, especially the approach of what is lower. Finally the meaning includes the attitude of condescension of a man in high position toward the people, and in general the setting to work on affairs. This hexagram is linked with the twelfth month (January-February), when after the winter solstice, the light power begins to ascend again.	Approach has supreme success. Perseverance furthers. When the eighth month comes, There will be misfortune.	The earth above the lake: The image of Approach. Thus the superior man is inexhaustible in his will to teach, And without limits in his tolerance and protection of the people.	Above K'un the Receptive, Earth	Below Tui the Joyous, Lake
20	Kuan  Contemplation (View)	A slight variation of tonal stress gives the Chinese name for this hexagram a double meaning. It means both contemplating and being seen, in the sense of being an example. These ideas are suggested by the fact that the hexagram can be understood as picturing a type of tower characteristic of ancient China. A tower of this kind commanded a wide view of the country; at the same time, when situated on a mountain, it became a landmark that could be seen for miles around. Thus the hexagram shows a ruler who contemplates the law of heaven above him and the ways of the people below, and who, by means of good government, sets a lofty example to the masses. This hexagram is linked with the eight month (September-October). The light-giving power retreats and the dark power is again on the increase. However, this aspect is not material in the interpretation of the hexagram as a whole.	Contemplation. The ablution has been made, but not yet the offering. Full of trust they look up to him.	The wind blows over the earth: The image of Contemplation. Thus the kings of old visited the regions of the world, contemplated the people and gave them instruction.	Above Sun the Gentle, Wind	Below K'un the Receptive, Earth
21	Shih Ho  Biting Through	This hexagram represents an open mouth (cf. hexagram 27) with an obstruction (in the fourth place) between the teeth. As a result the lips cannot meet. To bring them together one must bite energetically through the obstacle. Since the hexagram is made up of the trigrams for thunder and for lightning, it indicates how obstacles are forcibly removed in nature. Energetic biting through overcomes the obstacle that prevents joining of the lips; the storm with its thunder and lightning overcomes the disturbing tension in nature. Recourse to law and penalties overcomes the disturbances of harmonious social life caused by criminals and slanderers. The theme of this hexagram is a criminal lawsuit, in contradistinction to that of Sung, Conflict (6), which refers to civil suits.	Biting Through has success. It is favorable to let justice be administered.	Thunder and lighting: The image of Biting Through. Thus the kings of former times made firm the laws Through clearly defined penalties.	Above Li the Clinging, Fire	Below Chen the Arousing, Thunder
22	Pi  Grace	This hexagram shows a fire that breaks out of the secret depths of the earth and, blazing up, illuminates and beautifies the mountain, the heavenly heights. Grace-beauty of form-is necessary in any union if it is to be well ordered and pleasing rather than disordered and chaotic.	Grace has success in small matters It is favorable to undertake something.	Fire at the foot of the mountain: The image of Grace. Thus does the superior man proceed when clearing up current affairs. But he dare not decide controversial issues in this way.	Above Ken Keeping Still, Mountain	Below Li the Clinging, Fire
23	Po  Splitting Apart	The dark lines are about to mount upward and overthrow the last firm, light line by exerting a disintegrating influence on it. The inferior, dark forces overcome what is superior and strong, not by direct means, but by undermining it gradually and imperceptibly, so that it finally collapses. The lines of the hexagram present the image of a house, the top line being the roof, and because the roof is being shattered the house collapses. The hexagram belongs to the ninth month (October-November). The yin power pushes up ever more powerfully and is about to supplant the yang power altogether.	Splitting Apart. It does not further one to go anywhere.	The mountain rests on the earth: The image of Splitting Apart. Thus those above can ensure their position only by giving generously to those below.	Above Ken Keeping Still, Mountain	Below K'un the Receptive, Earth
24	Fu  Return (The Turning Point)	The idea of a turning point arises from the fact that after the dark lines have pushed all of the light lines upward and out of the hexagram, another light line enters the hexagram from below. The time of darkness is past. The winter solstice brings the victory of light. This hexagram is linked with the eleventh month, the month of the solstice (December-January).	Return. Success. Going out and coming in without error. Friends come without blame. To and fro goes the way. On the seventh day comes return. It furthers one to have somewhere to go.	Thunder within the earth: The image of The Turning Point. Thus the kings of antiquity closed the passes at the time of solstice. Merchants and strangers did not go about, and the ruler did not travel through the provinces.	Above K'un the Receptive, Earth	Below Chen the Arousing, Thunder
25	Wu Wang  Innocence (The Unexpected)	Ch'ien, heaven is above; Chen, movement, is below. The lower trigram Chen is under the influence of the strong line it has received form above, from heaven. When, in accord with this, movement follows the law of heaven, man is innocent and without guile. His mind is natural and true, unshadowed by reflection or ulterior designs. For wherever conscious purpose is to be seen, there the truth and innocence of nature have been lost. Nature that is not directed by the spirit is not true but degenerate nature. Starting out with the idea of the natural, the train of thought in part goes somewhat further and thus the hexagram includes also the idea of the fundamental or unexpected.	Innocence. Supreme success. Perseverance furthers. If someone is not as he should be he has misfortune, And it does not further him to undertake anything.	Under heaven thunder rolls: All things attain the natural state of innocence. Thus the kings of old, rich in virtue and in harmony with the time, fostered and nourished all beings.	Above Ch'ien the Creative, Heaven	Below Chen the Arousing, Thunder
26	Ta Chu  The Taming Power of the Great	The Creative is tamed by Ken, Keeping Still. This produces great power, a situation in contrast to that of the ninth hexagram, Hsiao Chu, The Taming Power of the Small, in which the Creative is tamed by the Gentle alone. There one weak line must tame five strong lines, but here four strong lines are restrained by two weak lines; in addition to a minister, there is a prince, and the restraining power therefore is afar stronger. The hexagram has a threefold meaning, expressing different aspects of the concept 'Holding firm.' Heaven within the mountain gives the idea of holding firm in the sense of holding together; the trigram Ken which holds the trigram ch'ien still, gives the idea of holding firm in the sense of holding back; the third idea is that of holding firm in the sense of caring for and nourishing. This last is suggested by the fact that a strong line at the top, which is the ruler of the hexagram, is honored and tended as a sage. The third of these meanings also attaches specifically to this strong line at the top, which represents the sage.	The Taming Power of the Great. Perseverance furthers. Not eating at home brings good fortune. It furthers one to cross the great water.	Heaven within the mountain: The image of The Taming Power of the Great. Thus the superior man acquaints himself with many sayings of antiquity and many deeds of the past in order to strengthen his character thereby.	Above Ken Keeping Still, Mountain	Below Ch'ien the Creative, Heaven
27	Corners of the Mouth (Providing Nourishment)	This hexagram is a picture of an open mouth; above and below are firm lines of the lips, and between them the opening. Starting with the mouth, through which we take food for nourishment, the thought leads to nourishment itself. Nourishment of oneself, specifically of the body, is represented in the three lower lines, while the three upper lines represent nourishment and care of others, in a higher, spiritual sense.	The Corners of the Mouth. Perseverance brings good fortune. Pay heed to the providing of nourishment and to what a man seeks to fill his own mouth with.	At the foot of the mountain, thunder: The image of Providing Nourishment . Thus the superior man is careful of his words and temperate in eating and drinking.	Above Ken Keeping Still, Mountain	Below Chen the Arousing, Thunder
28	Ta Kuo  Preponderance of the Great	This hexagram consists of four strong lines inside and two weak lines outside. When the strong are outside and the weak inside, all is well and there is nothing out of balance, nothing extraordinary in the situation. Here, however, the opposite is the case. The hexagram represents a beam that is thick and heavy in the middle but too weak at the ends. This is a condition that cannot last; it must be changed, must pass, or misfortune will result.	Preponderance of the Great. The ridgepole sags to the breaking point. It furthers one to have somewhere to go. Success.	The lake rises above the trees: The image of Preponderance of the Great. Thus the superior man, when he stands alone, is unconcerned and if he has to renounce the world he is undaunted.	Above Tui the Joyous, Lake	Below Sun the Gentle, Wind, Wood
29	K'an  The Abysmal (Water)	This hexagram consists of a doubling of the trigram K'an. It is one of the eight hexagrams in which doubling occurs. The trigram K'an means a plunging in. A yang line has plunged in between two yin lines and is closed in by them like water in a ravine. The trigram K'an is also the middle son. The Receptive has obtained the middle line of the Creative, and thus K'an develops. As an image it represents water, the water that comes from above and is in motion on earth in streams and rivers, giving rise to all life on earth. In man's world K'an represents the heart, the soul locked up within the body, the principle of light inclosed in the dark--that is, reason. The name of the hexagram, because the trigram is doubled, has the additional meaning, 'repetition of danger.' Thus the hexagram is intended to designate an objective situation to which one must become accustomed, not a subjective attitude. For danger due to a subjective attitude means either foolhardiness or guile. Hence too a ravine is used to symbolize danger; it is a situation in which a man is in the same pass as the water in a ravine, and, like the water, he can escape if he behaves correctly.	The Abysmal repeated. If you are sincere, you have success in your heart and whatever you do succeeds.	Water flows on uninterruptedly and reaches its foal: The image of the Abysmal repeated. Thus the superior man walks in lasting virtue and carries on the business of teaching.	Above K'an the abysmal, Water	Below K'an the abysmal, Water
30	Li  The Clinging, Fire	This hexagram is another double sign. The trigram Li means 'to cling to something,' and also 'brightness.' A dark line clings to two light lines, one above and one below--the image of an empty space between two strong lines, whereby the two strong lines are made bright. The trigram represents the middle daughter. The Creative has incorporated the central line of the Receptive, and thus Li develops. As an image, it is fire. Fire has no definite form but clings to the burning object and thus is bright. As water pours down from heaven, so fire flames up from the earth. While K'an means the soul shut within the body, Li stands for nature in its radiance.	The Clinging. Perseverance furthers. It brings success. Care of the cow brings good fortune.	That which is bright rises twice: The image of Fire. Thus the great man, by perpetuating this brightness, illumines the four quarters of the world.	Above Li the Clinging, Fire	Below Li the Clinging, Fire
31	Hsien  Influence (Wooing)	The name of the hexagram means 'universal,' 'general,' and in a figurative sense 'to influence,' 'to stimulate.' The upper trigram is Tui, the Joyous; the lower is Ken, Keeping still. By its persistent, quiet influence, the lower, rigid trigram stimulates the upper, weak trigram, which responds to this stimulation cheerfully and joyously. Ken, the lower trigram, is the youngest son; the upper, Tui, is the youngest daughter. Thus the universal mutual attraction between the sexes is represented. In courtship, the masculine principle must seize the initiative and place itself below the feminine principle. Just as the first part of book 1 begins with the hexagrams of heaven and earth, the foundations of all that exists, the second part begins with the hexagrams of courtship and marriage, the foundations of all social relationships.	Influence. Success. Perseverance furthers. To take a maiden to wife brings good fortune.	A lake on the mountain: The image of influence. Thus the superior man encourages people to approach him By his readiness to receive them.	Above Tui the Joyous, Lake	Below Ken Keeping Still, Mountain
32	Heng  Duration	The strong trigram Chen is above, the weak trigram Sun below. This hexagram is the inverse of the preceding one. In the latter we have influence, here we have union as an enduring condition. The two images are thunder and wind, which are likewise constantly paired phenomena. The lower trigram indicates gentleness within; the upper, movement without. In the sphere of social relationships, the hexagram represents the institution of marriage as the enduring union of the sexes. During courtship the young man subordinates himself to the girl, but in marriage, which is represented by the coming together of the eldest son and the eldest daughter, the husband is the directing and moving force outside, while the wife, inside, is gentle and submissive.	Duration. Success. No blame. Perseverance furthers. It furthers one to have somewhere to go.	Thunder and wind: the image of Duration. Thus the superior man stands firm and does not change has direction.	Above Chen, the Arousing, Thunder	Below Sun, the Gentle, Wind
33	Tun  Retreat	The power of the dark is ascending. The light retreats to security, so that the dark cannot encroach upon it. This retreat is a matter not of man's will but of natural law. Therefore in this case withdrawal is proper; it is the correct way to behave in order not to exhaust one's forces. In the calendar this hexagram is linked with the sixth month (July-August), in which the forces of winter are already showing their influence.	Retreat. Success. In what is small, perseverance furthers.	Mountain under heaven: the image of Retreat. Thus the superior man keeps the inferior man at a distance, not angrily but with reserve.	Above Ch'ien the Creative, Heaven	Below Ken Keeping Still, Mountain
34	Ta Chuang  The Power of the Great	The great lines, that is, the light, strong lines, are powerful. Four light lines have entered the hexagram from below and are about to ascend higher. The upper trigram is Chen, the Arousing; the lower is ch'ien, the Creative. Ch'ien is strong, Chen produces movement. The union of movement and strength gives the meaning of The Power of the Great. The hexagram is linked with the second month (March-April).	The Power of the Great. Perseverance furthers.	Thunder in heaven above: The image of The Power of the Great. Thus the superior man does not tread upon paths that do not accord with established order.	Above Chen the Arousing, Thunder	Below Ch'ien the Creative, Heaven
35	Chin  Progress	The hexagram represents the sun rising over the earth. It is therefore the symbol of rapid, easy progress, which at the same time means ever widening expansion and clarity.	Progress. The powerful prince is honored with horses in large numbers. In a single day he is granted audience three times.	The sun rises over the earth: The image of Progress. Thus the superior man himself brightens his bright virtue.	Above Li the Clinging, Fire	Below K'un the Receptive, Earth
36	Ming I  Darkening of the light	Here the sun has sunk under the earth and is therefore darkened. The name of the hexagram means literally 'wounding of the bright'; hence the individual lines contain frequent references to wounding. The situation is the exact opposite of that in the foregoing hexagram. In the latter a wise man at the head of affairs has able helpers, and in company with them makes progress; here a man of dark nature is in a position of authority and brings harm to the wise and able man.	Darkening of the light. In adversity. It furthers one to be persevering.	The light has sunk into the earth: The image of Darkening of the light. Thus does the superior man live with the great mass: He veils his light yet still shines.	Above K'un the Receptive, Earth	Below Li the Clinging, Fire
37	Chia Jen  The Family (The Clan)	The hexagram represents the laws obtaining within the family. The strong line at the top represents the father, the lowest the son. The strong line in the fifth place represents the husband, the yielding second line the wife. On the other hand, the two strong lines in the fifth and the third place represent two brothers, and the two weak lines correlated with them in the fourth and the second place stand for their respective wives. Thus all the connections and relationships within the family find their appropriate expression. Each individual line has the character according with its place. The fact that a strong line occupies the sixth place-where a weak line might be expected-indicates very clearly the strong leadership that must come from the head of the family. The line is to be considered here not in its quality as the sixth but in its quality as the top line. The Family shows the laws operative within the household that, transferred to outside life, keep the state and the world in order. The influence that goes out from within the family is represented by the symbol of the wind created by fire.	The Family. The perseverance of the woman furthers.	Wind comes forth from fire: The image of The Family. Thus the superior man has substance in his words and duration in his way of life.	Above Sun the Gentle, Wind	Below Li the Clinging, Fire
39	Chien  Obstruction	The hexagram pictures a dangerous abyss lying before us and a steep, inaccessible mountain rising behind us. We are surrounded by obstacles; at the same time, since the mountain has the attribute of keeping still, there is implicit a hint as to how we can extricate ourselves. The hexagram represents obstructions that appear in the course of time but that can and should be overcome. Therefore all the instruction given is directed to overcoming them.	Obstruction. The southwest furthers. The northeast does not further. It furthers one to see the great man. Perseverance brings good fortune.	Water on the mountain: The image of Obstruction. Thus the superior man turns his attention to himself and molds his character.	Above K'an the abysmal, Water	Below Ken Keeping Still, Mountain
40	Hsieh  Deliverance	Here the movement goes out of the sphere of danger. The obstacle has been removed, the difficulties are being resolved. Deliverance is not yet achieved; it is just in its beginning, and the hexagram represents its various stages.	Deliverance. The southwest furthers. If there is no longer anything where one has to go, Return brings good fortune. If there is still something where one has to go, Hastening brings good fortune.	Thunder and rain set in: The image of Deliverance. Thus the superior man pardons mistakes and forgives misdeeds.	Above Chen the Arousing, Thunder	Below K'an the abysmal, Water
41	Sun  Decrease	This hexagram represents a decrease of the lower trigram in favor of the upper, because the third line, originally strong, has moved up to the top, and the top line, originally weak, has replaced it. What is below is decreased to the benefit of what is above. This is out-and-out decrease. If the foundations of a building are decreased in strength and the upper walls are strengthened, the whole structure loves its stability. Likewise, a decrease in the prosperity of the people in favor of the government is out-and-out decrease. And the entire theme of the hexagram is directed to showing how this shift of wealth can take place without causing the sources of wealth can take place without causing the sources of wealth in the nation and its lower classes to fail.	Decrease combined with sincerity Brings about supreme good fortune without blame. One may be persevering in this. It furthers one to undertake something. How is this to be carried out? One may use two small bowls for the sacrifice.	At the foot of the mountain, the lake: The image of Decrease. Thus the superior man controls his anger and restrains his instincts.	Above Ken Keeping Still, Mountain	Below Tui the Joyous, Lake
42	I  Increase	The idea of increase is expressed in the fact that the strong lowest line of the upper trigram has sunk down and taken its place under the lower trigram. This conception also expresses the fundamental idea on which the Book of Changes is based. To rule truly is to serve. A sacrifice of the higher element that produces an increase of the lower is called an out-and-out increase: it indicates the spirit that alone has power to help the world.	Increase. It furthers one to undertake something. It furthers one to cross the great water.	Wind and thunder: the image of Increase. Thus the superior man, if he sees good, he imitates it. If he has faults, he rids himself of them.	Above Sun the Gentle, Wind	Below Chen the Arousing, Thunder
43	Ch'ien  The Creative	The first hexagram is made up of six unbroken lines. These unbroken lines stand for the primal power, which is light-giving, active, strong, and of the spirit. The hexagram is consistently strong in character, and since it is without weakness, its essence is power or energy. Its image is heaven. Its energy is represented as unrestricted by any fixed conditions in space and is therefore conceived of as motion. Time is regarded as the basis of this motion. Thus the hexagram includes also the power of time and the power of persisting in time, that is, duration. The power represented by the hexagram is to be interpreted in a dual sense in terms of its action on the universe and of its action on the world of men. In relation to the universe, the hexagram expresses the strong, creative action of the Deity. In relation to the human world, it denotes the creative action of the holy man or sage, of the ruler or leader of men, who through his power awakens and develops their higher nature.	The Creative works sublime success, Furthering through perseverance.	The movement of heaven is full of power. Thus the superior man makes himself strong and untiring.	Above Ch'ien the Creative, Heaven	Below Ch'ien the Creative, Heaven
44	Kou  Coming to Meet	This hexagram indicates a situation in which the principle of darkness, after having been eliminated, furtively and unexpectedly obtrudes again from within and below. Of its own accord the female principle comes to meet the male. It is an unfavorable and dangerous situation, and we must understand and promptly prevent the possible consequences. The hexagram is linked with the fifth month [June-July], because at the summer solstice the principle of darkness gradually becomes ascendant again.	Coming to Meet. The maiden is powerful. One should not marry such a maiden.	Under heaven, wind: The image of Coming to Meet. Thus does the prince act when disseminating his commands and proclaiming them to the four quarters of heaven.	Above Ch'ien the Creative, Heaven	Below Sun the Gentle, Wind
45	Ts'ui  Gathering Together (Massing)	This hexagram is related in form and meaning to Pi, Holding Togeather (8). In the latter, water is over the earth; here a lake is over the earth. But since the lake is a place where water collects, the idea of gathering together is even more strongly expressed here than in the other hexagram. The same idea also arises from the fact that in the present case it is two strong lines (the fourth and the fifth) that bring about the gather together, whereas in the former case one strong line (the fifth) stands in the midst of weak lines.	Gathering Together. Success. The king approaches his temple. It furthers one to see the great man. This brings success. Perseverance furthers. To bring great offerings creates good fortune. It furthers one to undertake something.	Over the earth, the lake: The image of Gathering Together. Thus the superior man renews his weapons in order to meet the unforeseen.	Above Tui the Joyous, Lake	Below K'un the Receptive, Earth
46	SHeng  Pushing Upward	The lower trigram, Sun, represents wood, and the upper, K'un, means the earth. Linked with this is the idea that wood in the earth grows upward. In contrast to the meaning of Chin, Progress (35), this pushing upward is associated with effort, just as a plant needs energy for pushing upward through the earth. That is why this hexagram, although it is connected with success, is associated with effort of the will. In Progress the emphasis is on expansion; Pushing Upward indicates rather a vertical ascent-direct rise from obscurity and lowliness to power and influence.	Pushing Upward has supreme success. One must see the great man, fear not. Departure toward the south brings good fortune.	Within the earth, wood grows: The image of Pushing Upward. Thus the superior man of devoted character heaps up small things in order to achieve something high and great.	Above K'un the Receptive, Earth	Below Sun the Gentle, Wind, Wood.
47	K'un  Oppression (Exhaustion)	The lake is above, water below; the lake is empty, dried up. Exhaustion is expressed in yet another way: at the top, a dark line is holding down two light line; below, a light line is hemmed in between two dark ones. The upper trigram belongs to the principle of darkness, the lower to the principle of light. Thus everywhere superior men are oppressed and held in restraint by inferior men.	Oppression. Success. Perseverance. The great man brings about good fortune, no blame. When one has something to say it is not believed.	There is not water in the lake: The image of Exhaustion. Thus the superior man stakes his life on following his will.	Above Tui the Joyous, Lake	Below K'an the abysmal, Water
48	Ching  The Well	Wood is below, water above. The wood goes down into the earth to bring up water. The image derives from the pole-and-bucket well of ancient China. The wood represents not the buckets, which in ancient times were made of clay, but rather the wooden poles by which the water is hauled up from the well. The image also refers to the world of plants, which lift water out of the earth by means of their fibers. The well from which water is drawn conveys the further idea of an inexhaustible dispensing of nourishment.	The Well. The town may be changed but the well cannot be changed. It neither decreases nor increases. They come and go and draw from the well. If one gets down almost to the water and the rope does not go all the way, or the jug breaks, it brings misfortune.\n	Water over wood: the image of The Well. Thus the superior man encourages the people at their work and exhorts them to help one another.	Above K'an the abysmal, Water	Below Sun the Gentle, Wind
49	Ko  Revolution (Molting)	The Chinese character for this hexagram means in its original sense an animal's pelt, which is changed in the course of the year by molting. From this word is carried over to apply to the 'moltings' in political life, the great revolutions connected with changes of governments. The two trigrams making up the hexagram are the same two that appear in K'uei, Oppostion (38), that is, the two younger daughters, Li and Tui. But while there the elder of the two daughters is above, and what results is essentially only an opposition of tendencies, here the younger daughter is above. The influences are in actual conflict, and the forces combat each other like fire and water (lake), each trying to destroy the other. Hence the idea of revolution.	Revolution. On your own day you are believed. Supreme success, Furthering through perseverance. Remorse disappears.	Fire in the lake: the image of Revolution. Thus the superior man sets the calendar in order and makes the seasons clear.	Above Tui the Joyous, Lake	Below Li the Clinging, Fire
50	Ting  The Caldron	The six lines construct the image of Ting, The Caldron; at the bottom are the legs, over them the belly, then come the ears (handles), and at the top the carrying rings. At the same time, the image suggests the idea of nourishment. The ting, cast of bronze, was the vessel that held the cooked viands in the temple of the ancestors and at banquets. The heads of the family served the food from the ting into the bowls of the guests. The Well (48) likewise has the secondary meaning of giving nourishment, but rather more in relation to the people. The ting, as a utensil pertaining to a refined civilization, suggests the fostering and nourishing of able men, which redounded to the benefit of the state. This hexagram and The Well are the only two in the Book of Changes that represent concrete, men-made objects. Yet here too the thought has its abstract connotation. Sun, below, is wood and wind; Li, above, is flame. Thus together they stand for the flame kindled by wood and wind, which likewise suggests the idea of preparing food.	The Caldron. Supreme good fortune. Success.	Fire over wood: The image of The Caldron. Thus the superior man consolidates his fate by making his position correct.	Above Li the Clinging, Fire	Below Sun the Gentle, Wind
51	Chen  The Arousing (Shock, Thunder)	The hexagram Chen represents the eldest son, who seizes rule with energy and power. A yang line develops below two yin lines and presses upward forcibly. This movement is so violent that it arouses terror. It is symbolized by thunder, which bursts forth from the earth and by its shock causes fear and trembling.	Shock brings success. Shock comes-oh, oh! Laughing words -ha, ha! The shock terrifies for a hundred miles and he does not let fall the sacrificial spoon and chalice.	Thunder repeated: the image of Shock. Thus, in fear and trembling, the superior man sets his life in order and examines himself.	Above Chen the Arousing, Thunder	Below Chen the Arousing, Thunder
52	Ken  Keeping Still, Mountain	The image of this hexagram is the mountain, the youngest son of heaven and earth. The male principle is at the top because it strives upward by nature; the female principle is below, since the direction of its movement has come to its normal end. In its application to man, the hexagram turns upon the problem of achieving a quiet heart. It is very difficult to bring quiet to the heart. While Buddhism strives for rest through an ebbing away of all movement in nirvana, the Book of Changes holds that rest is merely a state of polarity that always posits movement as its complement. Possibly the words of the text embody directions for the practice of yoga.	Keeping Still. Keeping his back still so that he no longer feels his body. He goes into his courtyard and does not see his people. No blame.	Mountains standing close together: The image of Keeping Still. Thus the superior man does not permit his thoughts to go beyond his situation.	Above Ken Keeping Still, Mountain	Below Ken Keeping Still, Mountain
53	Chien  Development (Gradual Progress)	This hexagram is made up of Sun (wood, penetration) above, i.e., without, and Ken (mountain, stillness) below, i.e., within. A tree on a mountain develops slowly according to the law of its being and consequently stands firmly rooted. This gives the idea of a development that proceeds gradually, step by step. The attributes of the trigrams also point to this: within is tranquility, which guards against precipitate actions, and without is penetration, which makes development and progress possible.	Development. The maiden Is given in marriage. Good fortune. Perseverance furthers.	On the mountain, a tree: The image of Development. Thus the superior man abides in dignity and virtue in order to improve the mores.	Above Sun the Gentle, Wind, Wood	Below Ken Keeping Still, Mountain
54	Kuei Mei  The Marrying Maiden	Above we have Chen, the eldest son, and below, Tui, the youngest daughter. The man leads and the girl follows him in gladness. The picture is that of the entrance of the girl into her husband's house. In all, there are four hexagrams depicting the relationship between husband and wife. Hsien, Influence, (31) , describes the attraction that a young couple have for each other; Heng, Duration (32), portrays the permanent relationships of marriage; Chien,Development (53), reflects the protracted, ceremonious procedures attending The Marrying Maiden (54), shows a young girl under the guidance of an older man who marries her.	The Marrying Maiden. Undertakings bring misfortune. Nothing that would further.	Thunder over the lake: The image of The Marrying Maiden. Thus the superior man understands the transitory, in the light of the eternity of the end.	Above Chen the Arousing, Thunder	Below Tui the Joyous, Lake
55	Feng  Abundance (Fullness)	Chen is movement; Li is flame, whose attribute is clarity. Clarity within, movement without-this produces greatness and abundance. The hexagram pictures a period of advanced civilization. However, the fact that development has reached a peak suggests that this extraordinary condition of abundance cannot be maintained permanently.	Abundance has success. The king attains abundance. Be not sad. Be like the sun at midday.	Both thunder and lightning come: The image of Abundance. Thus the superior man decides lawsuits and carries out punishments.	Above Chen the Arousing, Thunder	Below Li the Clinging, Fire
56	Lu  The Wanderer	The mountain, Ken, stands still; above it fire, Li, flames up and does not tarry. Therefore the two trigrams do not stay together. Strange lands and separation are the wanderer's lot.	The Wanderer. Success through smallness. Perseverance brings good fortune to the Wanderer.	Fire on the mountain: The image of The Wanderer. Thus the superior man is clear-minded, cautious in imposing penalties and protracts no lawsuits.	Above Li the Clinging, Fire	Below Ken Keeping Still, Mountain
57	Sun  The Gentle (The Penetrating, Wind)	Sun is one of the eight doubled trigrams. It is the eldest daughter and symbolizes wind or wood; it has for its attribute gentleness, which nonetheless penetrates like the wind or like growing wood with its roots. The dark principle, in itself rigid and immovable, is dissolved by the penetrating light principle, to which it subordinates itself in gentleness. In nature, it is the wind that disperses the gathered clouds, leaving the sky clear and serene. In human life it is penetrating clarity of judgment that thwarts all dark hidden motives. In the life of the community it is the powerful influence of a great personality that uncovers and breaks up those intrigues which shun the light of day.	The Gentle. Success through what is small. It furthers one to have somewhere to go. It furthers one to see the great man.	Winds following one upon the other: The image of The Gently Penetrating. Thus the superior man spreads his commands abroad and carries out his undertakings.	Above Sun the Gentle, Wind, Wood	Below Sun the Gentle, Wind, Wood
58	Tui  The Joyous, Lake	This hexagram, like sun, is one of the eight formed by doubling of a trigram. The trigram Tui denotes the youngest daughter; it is symbolized by the smiling lake, and its attribute is joyousness. Contrary to appearances, it is not the yielding quality of the top line that accounts for joy here. The attribute of the yielding or dark principle is not joy but melancholy. However, joy is indicated by the fact that there are two strong lines within, expressing themselves through the medium of gentleness. True joy, therefore, rests on firmness and strength within, manifesting itself outwardly as yielding and gentle.	The Joyous. Success. Perseverance is favorable.	Lakes resting one on the other: The image of The Joyous. Thus the superior man joins with his friends for discussion and practice.	Above Tui the Joyous, Lake	Below Tui the Joyous, Lake
59	Huan  Dispersion (Dissolution)	Wind blowing over water disperses it, dissolving it into foam and mist. This suggests that when a man's vital energy is dammed up within him (indicated as a danger by the attribute of the lower trigram), gentleness serves to break up and dissolve the blockage.	Dispersion. Success. The king approaches his temple. It furthers one to cross the great water. Perseverance furthers.	The wind drives over the water: The image of Dispersion. Thus the kings of old sacrificed to the Lord and built temples.	Above Sun the Gentle, Wind	Below K'an the abysmal, Water
60	Chieh  Limitation	A lake occupies a limited space. When more water comes into it, it overflows. Therefore limits must be set for the water. The image shows water below and water above, with the firmament between them as a limit. The Chinese word for limitation really denotes the joints that divide a bamboo stalk. In relation to ordinary life it means the thrift that sets fixed limits upon expenditures. In relation to the moral sphere it means the fixed limits that the superior man sets upon his actions-the limits of loyalty and disinterestedness.	Limitation. Success. Galling limitation must not be persevered in.\n	Water over lake: the image of Limitation. Thus the superior man creates number and measure and examines the nature of virtue and correct conduct.\n	Above K'an the abysmal, Water\n	Below Tui the Joyous, Lake\n
61	Chung Fu  Inner Truth	The wind blows over the lake and stirs the surface of the water. Thus visible effects of the invisible manifest themselves. The hexagram consists of firm lines above and below, while it is open in the center. This indicates a heart free of prejudices and therefore open to truth. On the other hand, each of the two trigrams has a firm line in the middle; this indicates the force of inner truth in the influences they present. The attributes of the two trigrams are: above, gentleness, forbearance toward inferiors; below, joyousness in obeying superiors. Such conditions create the basis of a mutual confidence that makes achievements possible. The character of fu ('truth') is actually the picture of a bird's foot over a fledgling. It suggests the idea of brooding. An egg is hollow. The light-giving power must work to quicken it from outside, but there must be a germ of life within, if life is to be awakened. Far-reaching speculations can be linked with these ideas.\n	Inner Truth. Pigs and fishes. Good fortune. It furthers one to cross the great water. Perseverance furthers.\n	Wind over lake: the image of Inner Truth. Thus the superior man discusses criminal cases in order to delay executions.\n	Above Sun the Gentle, Wind\n	Below Tui the Joyous, Lake\n
62	Hsiao Kuo  Preponderance of the Small	While in the hexagram Ta Kuo, Preponderance of the Great (28), the strong lines preponderate and are within, inclosed between weak lines at the top and bottom, the present hexagram has weak lines preponderating, though here again they are on the outside, the strong lines being within. This indeed is the basis of the exceptional situation indicated by the hexagram. When strong lines are outside, we have the hexagram I, Providing Nourishment (27), or Chung Fu, Inner Truth, (61); neither represents and exceptional state. When strong elements within preponderate, they necessarily enforce their will. This creates struggle and exceptional conditions in general. But in the present hexagram it is the weak element that perforce must mediate with the outside world. If a man occupies a position of authority for which he is by nature really inadequate, extraordinary prudence is necessary.\n	Preponderance of the Small. Success. Perseverance furthers. Small things may be done; great things should not be done. The flying bird brings the message: It is not well to strive upward, It is well to remain below. Great good fortune.\n	Thunder on the mountain: The image of Preponderance of the Small. Thus in his conduct the superior man gives preponderance to reverence. In bereavement he gives preponderance to grief. In his expenditures he gives preponderance to thrift.\n	Above Chen the Arousing, Thunder\n	Below Ken Keeping Still, Mountain\n
63	Chi Chi  After Completion	This hexagram is the evolution of T'ai Peace (11) . The transition from confusion to order is completed, and everything is in its proper place even in particulars. The strong lines are in the strong places, the weak lines in the weak places. This is a very favorable outlook, yet it gives reason for thought. For it is just when perfect equilibrium has been reached that any movement may cause order to revert to disorder. The one strong line that has moved to the top, thus effecting complete order in details, is followed by the other lines. Each moving according to its nature, and thus suddenly there arises again the hexagram P'i, Standstill (12).Hence the present hexagram indicates the conditions of a time of climax, which necessitate the utmost caution.\n	After Completion. Success in small matters. Perseverance furthers. At the beginning good fortune. At the end disorder.\n	Water over fire: the image of the condition In After Completion. Thus the superior man takes thought of misfortune and arms himself against it in advance.\n	Above K'an the abysmal, Water\n	Below Li the Clinging, Fire\n
64	Wei Chi  Before Completion	This hexagram indicates a time when the transition from disorder to order is not yet completed. The change is indeed prepared for, since all the lines in the upper trigram are in relation to those in the lower. However, they are not yet in their places. While the preceding hexagram offers an analogy to autumn, which forms the transition from summer to winter, this hexagram presents a parallel to spring, which leads out of winter's stagnation into the fruitful time of summer. With this hopeful outlook the Book of Changes come to its close.\n	Before Completion. Success. But if the little fox, after nearly completing the crossing, gets his tail in the water, There is nothing that would further.\n	Fire over water: The image of the condition before transition. Thus the superior man is careful in the differentiation of things so that each finds its place.\n	Above Li the Clinging, Flame\n	Below K'an the abysmal, Water\n
\.


--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY questions (id, created_at, updated_at, ask) FROM stdin;
\.


--
-- Name: questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('questions_id_seq', 1, false);


--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY schema_migrations (version) FROM stdin;
0
20140610182128
20140611040308
20140611044142
20140611065256
20140611065828
\.


--
-- Name: asks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY asks
    ADD CONSTRAINT asks_pkey PRIMARY KEY (id);


--
-- Name: hexes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY hexes
    ADD CONSTRAINT hexes_pkey PRIMARY KEY (hex_id);


--
-- Name: questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: unique_schema_migrations; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX unique_schema_migrations ON schema_migrations USING btree (version);


--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- Name: hexes; Type: ACL; Schema: public; Owner: postgres
--

REVOKE ALL ON TABLE hexes FROM PUBLIC;
REVOKE ALL ON TABLE hexes FROM postgres;
GRANT ALL ON TABLE hexes TO postgres;


--
-- PostgreSQL database dump complete
--

